menu:
  # 最後の/はWikiでは消さなければいけない、また最初も/じゃなくて./にする
  Project:
    link: /Project/
    submenus:
      Description: /Description/
      Contribution: /Contribution/
      Engineering: /Engineering/
      Safty: /Safty/
      Notebook: /Notebook/
      Excellence in another area: /Excellence_Area/
  Wet Lab: 
    link: /Wet-Lab/ 
    submenus:
      Results: /Results/
      Experiments: /Experiments/
      Parts: /Parts/
  Dry Lab: 
    link: /Dry-Lab/
    submenus:
      Model: /Model/
      Hardware: /Hardware/
  Human Practice: 
    link: /Human_Practice/
    submenus:
      Integrated Human Practice: /Human_Practices/
      Implementation: /Implementation/
      Education Communication: /Education/
  Team: 
    link: /Team/
    submenus: 
      Members: /Team/
      Attributions: /Attributions/
      Collaborations: /Collaborations/
      Partnership: /Partnership/
  Medal: 
    link : /Medal/

top_page:
  project_name: YEAST-AID
  project_description: Synbio Adhesive Bandage to Improve care of bedsores in an aging society
  sections:
    - title: Synbio Bandage to Change the Bedsore Care
      image: /assets/index/index-section-1.svg
      description: In Japan, the aging of population is becoming a serious problem. One of the medical conditions that should be taken care of regularly in an aging society is bedsores, which often occur in elderly people who spend a lot of time in bed. Our project proposes a new way to treat bedsores with bandages made by techniques of synthetic biology.
    - title: Cure with the Power of Yeasts
      image: /assets/index/index-section-2.svg
      description: |
        Inside of our bio-tech bandages is filled with genetically-modified yeasts, which will provide three core functions: 
        1.  Monitering of the healing of wounds through oxygen concentration
        2.  wounds sanitation by secreting antimicrobial peptides
        3.  detection of the bacterial infection  to wounds.
        These implementations will make it possible for non-medical personnel to manage pressure ulcers.
    - title: Cellfiber Keeps Yeasts Safely
      image: /assets/index/index-section-3.svg
      description: |
        The centerpiece of our product application is cell fiber, that is, thin, semi-permeable, hollow fibers with living cells aligned inside. While the semi-permeability makes cell fiber an ideal material of a bandage, hollow-structured fiber provides an innovative way of containing living cells. This technology has recentry invented in our university, and we pave a way to use the structure in the field of healthcare.
