menu:
  # Hoge: /hoge
  # Fuga: /fuga

top_page:
  # project_name: UTokyo 2021
  # project_description: Synbio Adhesive Bandage to Improve care of bedsores in an aging society
  # sections:
  #   - title: Synbio Bandage
  #     description: Our project aims to develop an adhesive bandage to treat bedsore, a typical symptom that requires continuous care in an aging society
  #   - title: Oxygen Sensing
  #     description: The heart of our biobrick design is to use yeast aerobic-anaerobic pathway, which hasn't achieved in iGEM projects. By altering fundamental genetic circuit that can sense the change in oxygen concentration level, our parts will make it possible to control yeast in response to oxygen.